package gui.viewandcontrollers.tableview;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class tableviewController {
	@FXML
	private TableView table;
	@FXML
	private TableColumn colTitulo;
	@FXML
	private TableColumn colIsbn;
	@FXML
	private TableColumn colAutor;
	@FXML
	private TableColumn colGenero;
	@FXML
	private TableColumn colPaginas;
	@FXML
	private Button nuevoButton;
	@FXML
	private Button editarButton;
	@FXML
	private Button eliminarButton;
	@FXML
	private Button cargarButton;
	@FXML
	private Button guardarButton;

	// Event Listener on Button[#nuevoButton].onAction
	@FXML
	public void nuevo(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#editarButton].onAction
	@FXML
	public void editar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#eliminarButton].onAction
	@FXML
	public void eliminar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#cargarButton].onAction
	@FXML
	public void cargar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#guardarButton].onAction
	@FXML
	public void guardar(ActionEvent event) {
		// TODO Autogenerated
	}
}
